# Generated by Django 4.1.1 on 2023-03-22 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_reviews_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="carts",
            name="qty",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
