# Generated by Django 4.1.1 on 2023-04-03 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_ordermodel"),
    ]

    operations = [
        migrations.DeleteModel(name="Address_user",),
    ]
